### ISSUE TITLE
Get a working Firefox build environment in NixOS

### ISSUE THREAD

**Issue by Jack5079** [mollersuite/tangent#25]
Clearly we have so many #15 that it's not possible for me to daily drive a WebKitGTK Tangent

Could use profiles so they can "install" Tangent side by side with Firefox
But basically firefox-gnome-theme exists so we already have libadwaita, we just need to port Methodsave and Tree Style Tab (firefox-gnome-theme uses Tab Center Reborn), and possibly abuse tab containers to get #4 

We also get updates and cross-platform for free

**Comment by Jack5079** [comment]
I have discovered Sideberry so I don't see a need for Tangent anymore

**Comment by nbitzz** [comment]
just.do that then ya dingus !!!

**Comment by Jack5079** [comment]
> I have discovered Sideberry so I don't see a need for Tangent anymore except if I can do deeper GNOME integration

I can't get it to be themed just right and I want a better color scheme so I might look into Tangent again

**Comment by nbitzz** [comment]
To be honest Tangent could probably just be a fork of Firefox with a few tweaks implemented, Pocket removed entirely (because Methodsave) and a few preinstalled extensions (ones for OS and Methodsave integration etc...)
