### ISSUE TITLE
App icon

### ISSUE THREAD

**Issue by Jack5079** [mollersuite/tangent#6]
https://developer.gnome.org/hig/guidelines/app-icons

Each app icon should have a simple, recognizable metaphor. Ideally this should have a clear and obvious relationship with the [app name](https://developer.gnome.org/hig/guidelines/app-naming.html). Common types of metaphors include:

- Physical objects directly related to what the app does (for example, a speaker for a music app).
- Physical objects which are at least somewhat related to the app’s domain, or to an older analog version of it (for example, a cassette tape for a podcasting app).
- Symbols related to the domain (for example, the “play” triangle for a video player).
- If the app has a distinctive UI, a simplified, stylized version of it.

Avoid metaphors that are unrelated to the name or function of the app, such as using characters or mascots. Also avoid using logos which rely on a specific visual style.

**Comment by Jack5079** [comment]
At first I wanted to have some edit of Arc's logo to be a T but I have no clue how that'll look

**Comment by Jack5079** [comment]
Also if anyone else attempts no you can't use a tan(x) graph it looks terrible

**Comment by Jack5079** [comment]
Nobody on the team is an artist so I think we'll do this after launch (if that ever happens FUCK WEBKIT)

**Comment by Jack5079** [comment]
Here's the Twitter PFP we're using as a tentative logo, using the Etcetera parent brand

This will hurt GNOME integration and of course the ability for users to tell Etcetera apps apart

![image](https://github.com/mollersuite/tangent/assets/29169102/d0ae95f9-4865-4730-ba46-73fe277a5803)

**Comment by nbitzz** [comment]
bottom left corner: Wavi Browser

**Comment by Jack5079** [comment]
Going with the bottom right fellow he's neat
![image](https://github.com/mollersuite/tangent/assets/29169102/16bb81a3-6920-45a9-9357-a8ff5d0c04ab)
